/* Script di creazione del database in MySql */

DROP DATABASE SEGRETERIA;

CREATE DATABASE IF NOT EXISTS SEGRETERIA;

USE SEGRETERIA;

CREATE TABLE IF NOT EXISTS STUDENTI (
    MATRICOLA       CHAR(10)       PRIMARY KEY,
    PASSWORD        VARCHAR(256)   NOT NULL,
    NOMESTUDENTE    VARCHAR(30)    NOT NULL,
    COGNOMESTUDENTE VARCHAR(30)    NOT NULL,
    CFUSTUDENTE     INT            NOT NULL,
    DATANASCITA     DATE           NOT NULL,
    MEDIA           DECIMAL(4, 2)  NOT NULL,
    CORSOSTUDENTE   VARCHAR(30)    NOT NULL,
    CONSTRAINT CHECK_MEDIA CHECK(MEDIA BETWEEN 18.0 AND 30.0)
);

INSERT INTO STUDENTI (MATRICOLA, PASSWORD, NOMESTUDENTE, COGNOMESTUDENTE, DATANASCITA, CFUSTUDENTE, MEDIA, CORSOSTUDENTE) VALUES ('0124002667', 'Vittoria_30', 'Gaetano', 'Romeo', '2003-01-22', 104, 26.8, 'Informatica');

CREATE TABLE IF NOT EXISTS ESAMI (
    NOMEESAME  VARCHAR(30),
    CORSOESAME VARCHAR(30),
    CFUESAME   INT NOT NULL,
    PRIMARY KEY (NOMEESAME, CORSOESAME),
    CONSTRAINT CHECK_CFU_ESAME CHECK(CFUESAME BETWEEN 3 AND 15)
);

INSERT INTO ESAMI (NOMEESAME, CORSOESAME, CFUESAME) VALUES ('Algoritmi e Strutture Dati', 'Informatica', 12);

CREATE TABLE IF NOT EXISTS APPELLI (
    NOMEESAME   VARCHAR(30),
    CORSOESAME  VARCHAR(30),
    DATAESAME   DATE NOT NULL,
    FOREIGN KEY (NOMEESAME, CORSOESAME) REFERENCES ESAMI (NOMEESAME, CORSOESAME)
);

INSERT INTO APPELLI (NOMEESAME, CORSOESAME, DATAESAME) VALUES ('Algoritmi e Strutture Dati', 'Informatica', '2023-09-25');
INSERT INTO APPELLI (NOMEESAME, CORSOESAME, DATAESAME) VALUES ('Algoritmi e Strutture Dati', 'Informatica', '2025-09-25');

CREATE TABLE IF NOT EXISTS PRENOTA (
    NOMEESAME        VARCHAR(30),
    CORSOESAME       VARCHAR(30),
    MATRICOLA        CHAR(10),
    DATAPRENOTAZIONE DATE NOT NULL,
    PRIMARY KEY (NOMEESAME, CORSOESAME, MATRICOLA),
    FOREIGN KEY (NOMEESAME, CORSOESAME) REFERENCES APPELLI (NOMEESAME, CORSOESAME),
    FOREIGN KEY (MATRICOLA)             REFERENCES STUDENTI (MATRICOLA)
);

INSERT INTO PRENOTA (NOMEESAME, CORSOESAME, MATRICOLA, DATAPRENOTAZIONE) VALUES ('Algoritmi e Strutture Dati', 'Informatica', '0124002667', '2023-09-01');

CREATE TABLE IF NOT EXISTS SUPERA (
    NOMEESAME  VARCHAR(30),
    CORSOESAME VARCHAR(30),
    MATRICOLA  CHAR(10),
    VOTO       INT NOT NULL,
    PRIMARY KEY (NOMEESAME, CORSOESAME, MATRICOLA),
    FOREIGN KEY (NOMEESAME, CORSOESAME) REFERENCES APPELLI (NOMEESAME, CORSOESAME),
    FOREIGN KEY (MATRICOLA)             REFERENCES STUDENTI (MATRICOLA),
    CONSTRAINT CHECK_VOTO CHECK (VOTO BETWEEN 18.0 AND 30.0)
);

INSERT INTO SUPERA (NOMEESAME, CORSOESAME, MATRICOLA, VOTO) VALUES ('Algoritmi e Strutture Dati', 'Informatica', '0124002667', 23);